### ISSUE TITLE
Readme/Preset suggestions

### ISSUE THREAD

**Issue by max-scopp** [ionic-team/stencil-eslint#8]
Just left a message in slack about `@stencil/strict-boolean-conditions` was set to "error", but it's quite rare that you actually need to do that explicitly.

I think it'll fit the "strict" preset better.

This is also not mentioned in the readme.
Will start a PR for the readme, if anyone has other suggestions, I'd be happy to include them, too.

**Comment by manucorporat** [comment]
Fixed!
