### ISSUE TITLE
Unused variable "h"

### ISSUE THREAD

**Issue by lazylazyllama** [ionic-team/stencil-eslint#9]
Is there any way to solve the unused variable "h" issue?:

`'h' is defined but never used.eslint(@typescript-eslint/no-unused-vars)`

Maybe stencil-eslint courld implement a rule that would override the typescript-eslint one?

**Comment by tarmooo** [comment]
But you use that variable h?

**Comment by lazylazyllama** [comment]
It's this weird jsx thing:

`The "h" namespace is used to import JSX types for elements and attributes. It is imported in order to avoid conflicting global JSX issues.`

So jsx does not work if i remove the `h` from `import { Component, h } from "@stencil/core";`

But i found a solution:

Replace:
`"@typescript-eslint/no-unused-vars": "warn",`
with: 
`"@typescript-eslint/no-unused-vars-experimental": "warn",`

**Comment by FirstVertex** [comment]
I added this to my `.eslintrc.json` to ignore a variable named "h"

```json
"@typescript-eslint/no-unused-vars": ["error", { 
  "varsIgnorePattern": "^h$"
}]
```
